version: '3.1'

networks:
  inception:
    name: inception

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/acardona/data/mariadb
      o: bind
      type: none
  # wordpress:
  #   name: wordpress
  #   driver: local
  #   driver_opts:
  #     device: /home/acardona/data/wordpress
  #     o: bind
  #     type: none

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    image: mariadb:42
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_USER_PASSWORD=${MYSQL_USER_PASSWORD}
  #   ports:
  #     -  3306:3306
    volumes:
      - mariadb:/var/lib/mysql
    networks:
     - inception
    restart: always

  # wordpressphp:
  #   container_name: wordpress
  #   build: ./requirements/wordpress/
  #   image: wordpress:42
  #   depends_on:
  #     mariadb:
  #       condition: service_healthy
  #   env_file:
  #     - .env
  #   volumes:
  #     - wordpress:/var/www/html
  #   networks:
  #     - inception
  #   restart: always

  # nginx:
  #   conainer_name: nginx
  #   build: ./requirements/nginx/
  #   image: nginx:42
  #   depends_on:
  #     wordpress:
  #       condition: service_healthy
  #   env_file:
  #     - .env
  #   ports:
  #     - 443:8043
  #   volumes:
  #     - wordpress:/var/www/html
  #   networks:
  #    - inception
  #   restart: always