version: '3.8'

networks:
  inception:
    name: inception

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    # image: mariadb:42
    # restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - v_mariadb:/var/lib/mysql
    networks:
     - inception

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress/
    # image: wordpress:42
    # image: wordpress:fpm
    # restart: always
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DEBUG="1"
    networks:
     - inception
    volumes:
      - v_wordpress:/var/www/html

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    # image: nginx:42
    # restart: always
    ports:
      - "80:80"
    volumes:
      # - ./wordpress.conf:/etc/nginx/conf.d/wordpress.conf
      - v_wordpress:/var/www/html
    networks:
     - inception

volumes:
  v_mariadb:
    name: v_mariadb
    driver: local
    driver_opts:
      device: ${VOLUMES_DIR}/mariadb
      o: bind
      type: none
  v_wordpress:
    name: v_wordpress
    driver: local
    driver_opts:
      device: ${VOLUMES_DIR}/wordpress
      o: bind
      type: none