version: '3.1'

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
            device: /home/acardona/Documents/Inception/test_volume/vmariadb
            o: bind
            type: none


services:
  mariadb:
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      -  3306:3306
    restart: always
    volumes:
      - mariadb:/var/lib/mysql

  # WordPressPHP:
  #   image: WordpressPHP
  #   env_file:
  #     -do_not_share.env
  #   restart: always
  #   ports:
  #     -9000:9000
  #   volumes:
  #     -${BASE_PATH}/WordpressPHP_volume

  # NGINX:
  #   image: NGINX
  #   env_file:
  #     -do_not_share.env
  #   restart: always
  #   ports:
  #     -443:443