version: '3.1'

networks:
  inception:
    name: inception

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/acardona/data/mariadb
      o: bind
      type: none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/acardona/data/wordpress
      o: bind
      type: none

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    image: mariadb:42
    restart: unless-stopped
    environment:
      - MYSQL_DB_NAME=${MYSQL_DB_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_USER_PASSWORD=${MYSQL_USER_PASSWORD}
  #   ports:
  #     -  3306:3306
    volumes:
      - mariadb:/var/lib/mysql
    networks:
     - inception

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    image: wordpress:42
    depends_on:
      mariadb:
        condition: service_started
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_NAME=${MYSQL_DB_NAME}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_USER_PASSWORD}
      - WORDPRESS_DB_HOST=mariadb:3306
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    image: nginx:42
    depends_on:
      wordpress:
        condition: service_started
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 443:8043
    volumes:
      - wordpress:/var/www/html
    networks:
     - inception